### ISSUE TITLE
visitorName lost when window closed

### ISSUE THREAD

**Issue by tvigil** [bradmb/sl.js#11]
I am using the SLjs.Button method of launching the chat window, and specifying a user name in the config with the "visitorName" parameter.  I found that when closing the window, the user identity specified by the visitorName parameter is lost.  When clicking the trigger button to open the window again, it prompts for a new user name.
Awesome project!! Thanks! :)

**Comment by tvigil** [comment]
Also, if you accidentally click on the triggering button twice, that also has the effect of dropping the visitorName.

**Comment by tvigil** [comment]
Also,  I noticed that when I comment on issues here, I get rude messages from Brad on Slack.  Very strange. XD

**Comment by bradmb** [comment]
This issue has been fixed. A NuGet package update has been deployed and the releases page contains the latest .zip file.
